<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Macademy\Trainee\ViewModel\ReviewMessage $ReviewsViewModel */
$ReviewsViewModel = $block->getViewModel();
?>

<?php if ($ReviewsViewModel->isLoggedIn()): ?>
    <p>El usuario está logueado</p>
    <p>Bienvenido, <?= $block->escapeHtml($ReviewsViewModel->getCustomerName()) ?></p>
<?php else: ?>
    <p>El usuario no está logueado</p>
<?php endif; ?>


    <button type="submit">Enviar Opinión</button>
    <br>
    <form action="<?= $block->getUrl('reviews/index/save') ?>" method="post">
        <input type="text" name="nombre" placeholder="Ingresa tu nombre" required>
        <button type="submit">Guardar</button>
    </form>

